services:
    app.ui.action.home_action:
        class: App\Ui\Action\HomeAction
        arguments:
            - '@app.infrastructure.repository.board_repository'
            - '@templating'

    app.ui.action.security.form_login_action:
        class: App\Ui\Action\Security\FormLoginAction
        arguments:
            - '@security.authentication_utils'
            - '@templating'

    app.ui.action.collection_nav_action:
        class: App\Ui\Action\CollectionNavAction
        arguments:
            - '@tactician.commandbus'
            - '@request_stack'
            - '@templating'

    app.ui.action.menu.topbar_action:
        class: App\Ui\Action\Menu\TopbarAction
        arguments:
            - '@tactician.commandbus'
            - '@security.token_storage'
            - '@templating'

    #
    # Board
    #
    app.ui.action.board.add_action:
        class: App\Ui\Action\Board\AddAction
        arguments:
            - '@tactician.commandbus'
            - '@form.factory'
            - '@templating'
            - '@router'
            - '@session.flash_bag'

    app.ui.action.board_action:
        class: App\Ui\Action\BoardAction
        arguments:
            - '@app.infrastructure.repository.board_repository'
            - '@templating'

    #
    # Collection
    #

    app.ui.action.collection_action:
        class: App\Ui\Action\CollectionAction
        arguments:
            - '@tactician.commandbus'
            - '@templating'

    app.ui.action.collection.add_action:
        class: App\Ui\Action\Collection\AddAction
        arguments:
            - '@tactician.commandbus'
            - '@form.factory'
            - '@templating'
            - '@router'
            - '@session.flash_bag'

    app.ui.action.collection.edit_action:
        class: App\Ui\Action\Collection\EditAction
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@tactician.commandbus'
            - '@form.factory'
            - '@templating'
            - '@router'
            - '@session.flash_bag'

    app.ui.action.collection.remove_action:
        class: App\Ui\Action\Collection\RemoveAction
        arguments:
            - '@tactician.commandbus'
            - '@router.default'
            - '@session.flash_bag'

    #
    # Bookmarks
    #

    app.ui.action.bookmark.add_action:
        class: App\Ui\Action\Bookmark\AddAction
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@tactician.commandbus'
            - '@form.factory'
            - '@templating'
            - '@router'
            - '@session.flash_bag'

    app.ui.action.bookmark.edit_action:
        class: App\Ui\Action\Bookmark\EditAction
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
            - '@tactician.commandbus'
            - '@form.factory'
            - '@templating'
            - '@router'
            - '@session.flash_bag'

    app.ui.action.bookmark.remove_action:
        class: App\Ui\Action\Bookmark\RemoveAction
        arguments:
            - '@tactician.commandbus'
            - '@router.default'
            - '@session.flash_bag'
