services:
    app.application.command.create_bookmark_command_handler:
        class: App\Application\Command\CreateBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.bookmark.unique_url_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\CreateBookmarkCommand }

    app.application.command.update_bookmark_command_handler:
        class: App\Application\Command\UpdateBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.bookmark.unique_url_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\UpdateBookmarkCommand }

    app.application.command.remove_bookmark_command_handler:
        class: App\Application\Command\RemoveBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\RemoveBookmarkCommand }

    app.application.command.create_collection_command_handler:
        class: App\Application\Command\CreateCollectionCommandHandler
        arguments:
            - '@app.infrastructure.repository.board_repository'
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.collection.unique_title_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\CreateCollectionCommand }

    app.application.command.update_collection_command_handler:
        class: App\Application\Command\UpdateCollectionCommandHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.collection.unique_title_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\UpdateCollectionCommand }

    app.application.command.remove_collection_command_handler:
        class: App\Application\Command\RemoveCollectionCommandHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\RemoveCollectionCommand }

    app.application.command.board.create_board_command_handler:
        class: App\Application\Command\Board\CreateBoardCommandHandler
        arguments:
            - '@app.infrastructure.repository.board_repository'
            - '@app.infrastructure.repository.collaborator_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Board\CreateBoardCommand }
