services:
    app.application.command.create_bookmark_command_handler:
        class: App\Application\Command\CreateBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\CreateBookmarkCommand }

    app.application.command.update_bookmark_command_handler:
        class: App\Application\Command\UpdateBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\UpdateBookmarkCommand }
