services:
    app.application.command.bookmark.create_bookmark_command_handler:
        class: App\Application\Command\Bookmark\CreateBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.bookmark.unique_url_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Bookmark\CreateBookmarkCommand }

    app.application.command.bookmark.update_bookmark_command_handler:
        class: App\Application\Command\Bookmark\UpdateBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.bookmark.unique_url_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Bookmark\UpdateBookmarkCommand }

    app.application.command.bookmark.remove_bookmark_command_handler:
        class: App\Application\Command\Bookmark\RemoveBookmarkCommandHandler
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Bookmark\RemoveBookmarkCommand }

    app.application.command.collection.create_collection_command_handler:
        class: App\Application\Command\Collection\CreateCollectionCommandHandler
        arguments:
            - '@app.infrastructure.repository.board_repository'
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.collection.unique_title_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Collection\CreateCollectionCommand }

    app.application.command.collection.update_collection_command_handler:
        class: App\Application\Command\Collection\UpdateCollectionCommandHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@app.domain.rules.collection.unique_title_checker'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Collection\UpdateCollectionCommand }

    app.application.command.collection.remove_collection_command_handler:
        class: App\Application\Command\Collection\RemoveCollectionCommandHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Collection\RemoveCollectionCommand }

    app.application.command.board.create_board_command_handler:
        class: App\Application\Command\Board\CreateBoardCommandHandler
        arguments:
            - '@app.infrastructure.repository.board_repository'
            - '@app.infrastructure.repository.collaborator_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Board\CreateBoardCommand }

    app.application.command.board.update_collaborators_command_handler:
        class: App\Application\Command\Board\UpdateCollaboratorsCommandHandler
        arguments:
            - '@app.infrastructure.repository.collaborator_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Board\UpdateCollaboratorsCommand }

    app.application.command.board.update_board_command_handler:
        class: App\Application\Command\Board\UpdateBoardCommandHandler
        tags:
            - { name: tactician.handler, command: App\Application\Command\Board\UpdateBoardCommand }

    app.application.command.board.add_collaborator_command_handler:
        class: App\Application\Command\Board\AddCollaboratorCommandHandler
        arguments:
            - '@app.domain.rules.collaborator.unique_checker'
            - '@app.infrastructure.repository.collaborator_repository'
            - '@app.application.event.event_recorder'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Board\AddCollaboratorCommand }

    app.application.command.board.remove_collaborator_command_handler:
        class: App\Application\Command\Board\RemoveCollaboratorCommandHandler
        arguments:
            - '@app.infrastructure.repository.collaborator_repository'
            - '@app.application.event.event_recorder'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Board\RemoveCollaboratorCommand }

    app.application.command.collection.export_command_handler:
        class: App\Application\Command\Collection\ExportCommandHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@app.application.exporter.collection_exporter'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Collection\ExportCommand }
