services:
    app.ui.form.type.user_autocomplete_type:
        class: App\Ui\Form\Type\UserAutocompleteType
        arguments:
            - '@app.infrastructure.repository.user_repository'
        tags:
            - { name: form.type }

    app.infrastructure.form.extension.file_type_extension:
        class: App\Infrastructure\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
