services:
    app.infrastructure.mail.collaborator_added_mail:
        class: App\Infrastructure\Mail\CollaboratorAddedMail
        arguments:
            - '@mailer'
            - '@templating'

    app.infrastructure.mail.collaborator_removed_mail:
        class: App\Infrastructure\Mail\CollaboratorRemovedMail
        arguments:
            - '@mailer'
            - '@templating'
