services:
    app.infrastructure.graph_ql.mutator.bookmark_mutator:
        class: App\Infrastructure\GraphQL\Mutator\BookmarkMutator
        arguments:
            - '@tactician.commandbus'
            - '@app.infrastructure.graph_ql.normalizer.bookmark_normalizer'
        tags:
            - { name: overblog_graphql.mutation, alias: "bookmark", method: "mutateBookmark" }

    app.infrastructure.graph_ql.mutator.collection_mutator:
        class: App\Infrastructure\GraphQL\Mutator\CollectionMutator
        arguments:
            - '@tactician.commandbus'
            - '@app.infrastructure.graph_ql.normalizer.collection_normalizer'
        tags:
            - { name: overblog_graphql.mutation, alias: "collection", method: "mutateCollection" }
