services:
    app.application.query.collection_nav_query_handler:
        class: App\Application\Query\CollectionNavQueryHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Query\CollectionNavQuery }

    app.application.query.collection_view_query_handler:
        class: App\Application\Query\CollectionViewQueryHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@app.infrastructure.repository.bookmark_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Query\CollectionViewQuery }

    app.application.query.board_nav_query_handler:
        class: App\Application\Query\BoardNavQueryHandler
        arguments:
            - '@app.infrastructure.repository.board_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Query\BoardNavQuery }

    app.application.query.board_list_query_handler:
        class: App\Application\Query\BoardListQueryHandler
        arguments:
            - '@app.infrastructure.repository.board_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Query\BoardListQuery }
