services:
    app.application.query.collection_nav_query_handler:
        class: App\Application\Query\CollectionNavQueryHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Query\CollectionNavQuery }

    app.application.query.collection_view_query_handler:
        class: App\Application\Query\CollectionViewQueryHandler
        arguments:
            - '@app.infrastructure.repository.collection_repository'
            - '@app.infrastructure.repository.bookmark_repository'
        tags:
            - { name: tactician.handler, command: App\Application\Query\CollectionViewQuery }
