services:
    app.infrastructure.repository.bookmark_repository:
        class: App\Infrastructure\Repository\BookmarkRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            
    app.infrastructure.repository.collection_repository:
        class: App\Infrastructure\Repository\CollectionRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    app.infrastructure.repository.collaborator_repository:
        class: App\Infrastructure\Repository\CollaboratorRepository
        arguments:
            - '@doctrine.orm.entity_manager'
