services:
    app.domain.rules.bookmark.unique_url_checker:
        class: App\Domain\Rules\Bookmark\UniqueUrlChecker
        arguments:
            - '@app.infrastructure.repository.bookmark_repository'

    app.domain.rules.collection.unique_title_checker:
        class: App\Domain\Rules\Collection\UniqueTitleChecker
        arguments:
            - '@app.infrastructure.repository.collection_repository'
