services:
    app.infrastructure.validator.constraints.container_expression_validator:
        class: App\Infrastructure\Validator\Constraints\ContainerExpressionValidator
        arguments:
            - '@service_container'
        tags:
            - { name: validator.constraint_validator, alias: validator.container_expression }
