home:
    path: /
    defaults: { _controller: app.ui.action.home_action }
    methods: [GET]

login:
    path: /login
    defaults: { _controller: app.ui.action.security.form_login_action }
    methods: [GET]

login_check:
    path: /login-check

logout:
    path: /logout

board_add:
    path: /board/add
    defaults: { _controller: app.ui.action.board.add_action }
    methods: [GET, POST]

board:
    path: /board/{boardId}
    defaults: { _controller: app.ui.action.board_action }
    methods: [GET]

collection_add:
    path: /board/{boardId}/collection/add
    defaults: { _controller: app.ui.action.collection.add_action }
    methods: [GET, POST]
    requirements:
        boardId: \d+

collection:
    path: /board/{boardId}/collection/{collectionId}
    defaults: { _controller: app.ui.action.collection_action }
    methods: [GET]
    requirements:
        boardId: \d+
        collectionId: \d+

collection_edit:
    path: /board/{boardId}/collection/{collectionId}/edit
    defaults: { _controller: app.ui.action.collection.edit_action }
    methods: [GET, POST]
    requirements:
        boardId: \d+
        collectionId: \d+

collection_remove:
    path: /board/{boardId}/collection/{collectionId}
    defaults: { _controller: app.ui.action.collection.remove_action }
    methods: [DELETE]
    requirements:
        boardId: \d+
        collectionId: \d+

bookmark_add:
    path: /board/{boardId}/collection/{collectionId}/bookmark/add
    defaults: { _controller: app.ui.action.bookmark.add_action }
    methods: [GET, POST]
    requirements:
        boardId: \d+
        collectionId: \d+

bookmark_edit:
    path: /board/{boardId}/collection/{collectionId}/bookmark/{bookmarkId}/remove
    defaults: { _controller: app.ui.action.bookmark.edit_action }
    methods: [GET, POST]
    requirements:
        boardId: \d+
        collectionId: \d+
        bookmarkId: \d+

bookmark_remove:
    path: /board/{boardId}/collection/{collectionId}/bookmark/{bookmarkId}/remove
    defaults: { _controller: app.ui.action.bookmark.remove_action }
    methods: [DELETE]
    requirements:
        boardId: \d+
        collectionId: \d+
        bookmarkId: \d+
