language: generic

sudo: required

services:
  - docker

before_install:
  - docker pull manala/ansible-debian:wheezy
  - docker pull manala/ansible-debian:jessie

script:
  - make lint@wheezy
  - make test@wheezy
  - make lint@jessie
  - make test@jessie

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
