App\Application\Query\UserAutocompleteQuery:
    properties:
        term:
            - NotBlank: ~
            - Type: { type: string }
        boardId:
            - NotBlank: ~
            - Type: { type: int }
            - Range: { min: 1 }
