App\Application\Command\Board\AddCollaboratorCommand:
    properties:
        board:
            - NotBlank: ~
        user:
            - NotBlank: ~
            - App\Infrastructure\Validator\Constraints\ContainerExpression:
                expression: "service('app.domain.rules.collaborator.unique_checker').isUnique(this.board, this.user)"
                message: "Cet utilisateur a déjà été ajouté aux collaborateurs."
