# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        App\Infrastructure\Security\User\SymfonyUser:
            algorithm: bcrypt
            cost:      12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: 'app.infrastructure.security.user.symfony_user_provider'

        # api_key_user_provider:
        #     id: 'app.infrastructure.security.api.api_key_user_provider'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                require_previous_session: false
            logout:
                path: logout


        # graphql:
        #     pattern: ^/graphql
        #     stateless: true
        #     provider: api_key_user_provider
        #     simple_preauth:
        #         authenticator: app.infrastructure.security.api_key_authenticator

    access_control:
        # - { path: ^/graphql, roles: ROLE_API }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
