App\Domain\Model\Board:
    type:   entity
    table:  board
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            unique: true
