App\Domain\Model\Bookmark:
    type:   entity
    table:  bookmark
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            unique: true
        title:
            type: string
