App\Domain\Model\Collection:
    type:   entity
    table:  collection
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
    manyToOne:
        board:
            targetEntity: App\Domain\Model\Board
            joinColumn:
                onDelete: CASCADE
    uniqueConstraints:
        unique_title_idx:
            columns: [board_id, title]
