App\Domain\Model\User:
    type:   entity
    table:  user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            unique: true
        password:
            type: string
        firstname:
            type: string
        lastname:
            type: string
        admin:
            type: boolean
