Bookmark:
    type: object
    config:
        description: Bookmark
        fields:
            id:
                type: "ID!"
                description: "Id"
            url:
                type: "String!"
                description: "Url"
            title:
                type: "String!"
                description: "Title"

Bookmarks:
    type: object
    config:
        description: Bookmarks
        fields:
            total:
                type: "Int"
            offset:
                type: "Int"
            limit:
                type: "Int"
            edges:
                type: "[Bookmark]"
