Collection:
    type: object
    config:
        description: Collection
        fields:
            id:
                type: "ID!"
                description: "Id"
            title:
                type: "String!"
                description: "Title"
            bookmarks:
                type: "Bookmarks"
                args:
                    offset:
                        type: "Int"
                        defaultValue: 0
                    limit:
                        type: "Int"
                        defaultValue: 10
                resolve: '@=resolver("collectionBookmarks", [value, args, info])'

Collections:
    type: object
    config:
        description: Collections
        fields:
            total:
                type: "Int"
            offset:
                type: "Int"
            limit:
                type: "Int"
            edges:
                type: "[Collection]"
