Mutation:
    type: object
    config:
        fields:
            createBookmark:
                type: "Bookmark!"
                resolve: "@=mutation('createBookmark', [args['url'], args['title'], args['collectionId']])"
                args:
                    title:
                        type: "String!"
                    url:
                        type: "String!"
                    collectionId:
                        type: "Int!"
            updateBookmark:
                type: "Bookmark!"
                resolve: "@=mutation('updateBookmark', [args['id'], args['url'], args['title'], args['collectionId']])"
                args:
                    id:
                        type: "Int!"
                    title:
                        type: "String!"
                    url:
                        type: "String!"
                    collectionId:
                        type: "Int!"
            removeBookmark:
                type: "Boolean"
                resolve: "@=mutation('removeBookmark', [args['id']])"
                args:
                    id:
                        type: "Int"
            createCollection:
                type: "Collection!"
                resolve: "@=mutation('createCollection', [args['title']])"
                args:
                    title:
                        type: "String!"
            updateCollection:
                type: "Collection!"
                resolve: "@=mutation('updateCollection', [args['id'], args['title']])"
                args:
                    id:
                        type: "Int!"
                    title:
                        type: "String!"
            removeCollection:
                type: "Boolean"
                resolve: "@=mutation('removeCollection', [args['id']])"
                args:
                    id:
                        type: "Int"
