App\Application\Command\Bookmark\UpdateBookmarkCommand:
    properties:
        id:
            - NotBlank: ~
            - Type: { type: integer }
        url:
            - NotBlank: ~
            - Url: ~
            - App\Infrastructure\Validator\Constraints\ContainerExpression:
                expression: "service('app.domain.rules.bookmark.unique_url_checker').isUnique(this.url, this.id)"
                message: "Il existe déjà un favoris avec cette url."
        title:
            - NotBlank: ~
            - Type: { type: string }
        collectionId:
            - NotBlank: ~
            - Type: { type: integer }
